### ISSUE TITLE
When launch the program, it tells me could not found the game installation.

### ISSUE THREAD

**Issue by toshiya14** [Soreepeong/FFXIV-FontChanger#1]
When launch the program, it tells me could not found the game installation.
But I confirm that the path is correct to the `game` folder of the game.

![图片](https://user-images.githubusercontent.com/13333533/171034702-a51a2de0-881a-4173-8f84-66e16b5e991d.png)
![图片](https://user-images.githubusercontent.com/13333533/171034726-a1405ff3-9678-49b1-94fb-6f333e1b65ee.png)
![图片](https://user-images.githubusercontent.com/13333533/171034786-4227f095-32ea-4719-a694-967b4819aba5.png)

**Comment by toshiya14** [comment]
In this case, if I create the chnaxis project and change the font, it would not display some in-game symbols and characters.

![图片](https://user-images.githubusercontent.com/13333533/171035140-67a8589a-4590-46c8-bfc8-c924abc33cc9.png)

**Comment by toshiya14** [comment]
![图片](https://user-images.githubusercontent.com/13333533/171035586-ae45b1e7-bef3-46d8-bbab-62172fa86110.png)

I think I resolved this problem by having some tries.

I added a prerendered range with `U+E000~F8FF Private Use Area`.
And finally it seems to be OK.

**Comment by Soreepeong** [comment]
Do you have international client installed? If not, then it probably would display that message on startup. Was that the problem?

Regarsless, I should make it default to ChnAXIS/KrnAXIS if international client hasn't been found by default.

**Comment by toshiya14** [comment]
@Soreepeong It just gives me an alert and confusing me. I have set the correct chinese game path, but still tells me game not found. And some in-game fonts becoming "=".
But seems it is do not block me with following actions. And I have find out the way to fix the "=".
So, I closed the tickets.

**Comment by Soreepeong** [comment]
It will try to read files from global client on startup, and if it doesn't exist, it will show that message at the moment. I believe that was the source of confusion; I'll have that fixed.

**Comment by fatinghenji** [comment]
可以麻烦您详细讲一下`I added a prerendered range with U+E000~F8FF Private Use Area.`这个部分吗？
遇到了相同的问题

**Comment by toshiya14** [comment]
@fatinghenji 

首先抱歉恢复晚了，FF14 内置使用了这个区间作为 一些特殊图标的定义。
所以，这一部分，需要增加为从原有的字体中提取。

所以这个区间，需要在 ChnAxis 中导入，但是不要在自定义的字体中导入该区间。
懒人直接抄作业：下面贴上我自用的设定，你可以直接把里面的字体直接换成你需要的。

https://gist.github.com/toshiya14/38bce63a2bf1f26cb7216e62afa94905
