### ISSUE TITLE
Transformation Matrix seems not work

### ISSUE THREAD

**Issue by GpointChen** [Soreepeong/FFXIV-FontChanger#14]
I was trying to make all added fonts use the same glyphs by configuring the transformation matrix, e.g. using 12-size Noto Sans for all fonts and set transformation matrix 0.8x for AXIS_96, 1x for AXIS_12, 3x for AXIS_36, and so on. However, the exported in-game fonts look really small.

My config for lobby font and main game font: [XivRes.FontGenerator64.zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/10420387/XivRes.FontGenerator64.zip)

## Problem Description

The preview looks good before exporting:

![https://cdn.discordapp.com/attachments/468349920823476235/1064182081707577417/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064182081707577417/image.png)

After exporting, the preview looks the same, but you will see that the preview has changed after switching to a different font and then switching back. The CJK character glyphs are not scaled up.

![https://cdn.discordapp.com/attachments/468349920823476235/1064184014816153621/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064184014816153621/image.png)

Also, in-game font are all in small size without strenching/scaling.

![https://cdn.discordapp.com/attachments/468349920823476235/1064171219676581938/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064171219676581938/image.png)

![https://cdn.discordapp.com/attachments/468349920823476235/1064171614750638210/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064171614750638210/image.png)

But in the config file I attach above, the transformation matrices are saved correctly.

## Compare

For show the font size differences, here are the screenshots if I don't use the transformation matrix but change the font size just like in normal case. That is, using 12-size Noto Sans for AXIS_12, 36-size Noto Sans for AXIS_36, etc., with transformation matrix all set to [1, 0, 0, 1].

![https://cdn.discordapp.com/attachments/468349920823476235/1064166300580069466/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064166300580069466/image.png)

![https://cdn.discordapp.com/attachments/468349920823476235/1064166979830820924/image.png](https://cdn.discordapp.com/attachments/468349920823476235/1064166979830820924/image.png)

Thank you for help in advance.

* Edited as some images were not showing up correctly.

**Comment by Soreepeong** [comment]
I'll take a look once I get a time to get it to compile again. For some reason it isn't even compiling after reinstalling Windows. Should be possible before this week passes!

**Comment by Soreepeong** [comment]
[XivRes.FontGenerator64.zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/10426336/XivRes.FontGenerator64.zip)

Actually, try this build.

**Comment by GpointChen** [comment]
> [XivRes.FontGenerator64.zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/10426336/XivRes.FontGenerator64.zip)
> 
> Actually, try this build.

Thanks for your help.

It works but the fonts seem to use different glyphs. For example, I got only 8 1024x1024 `.tex` files (4 for main game font and 4 for lobby font) when I used 0.0.0.4 build, but the newer one generates 80+ 1024x1024 `.tex` files in total.

I expected the fonts use the same glyphs, so the files will be smaller with the cost of quality.

**Comment by Soreepeong** [comment]
I don't think that's possible; previous version resulting in 4 tex files is an error in that it reused 9.6 glyphs for 36. You may want to use 4096x4096 tex files instead. Different transformation matrix results in different glyphs rendered.

Though, I get 13x1024x1024 for main, and 37x1024x1024 for lobby (probably due to huge TrumpGothic replacement). Should fit in far fewer number of tex files if you go for 4k x 4k.

**Comment by GpointChen** [comment]
Yeah I know I can use 4096x4096 but I would like to make the font files smaller. It seems that my idea is not feasible if the fonts in different sizes cannot reuse the same glyphs. I may need to figure out the other ways.

Anyway, thank for your help again. The issue of transformation matrices is fixed so the thread can be closed I think.
