### ISSUE TITLE
No kerning in generated fonts

### ISSUE THREAD

**Issue by endervad** [Soreepeong/FFXIV-FontChanger#15]
<details>
  <summary><i>Off-topic preface</i></summary>
  Hi! I've used your tool before to integrate cyrillics into the game fonts - thanks a lot for it! This time I decided to remaster AXIS font since default handling and look of cyrillics could be a lot better, especially at smaller font sizes. However, there are some issues that stop me from releasing those fixes in public, so I'm reporting them in hopes you find time to fix them. Thank you in advance!
</details>

It looks like the program doesn't export kerning at all - neither the default in-game one, nor custom font's one.

Side-to-side comparison against in-game text with the same font in preview with kerning enabled.

Without modded font at all:
<img width="117" alt="Screenshot 2024-09-17 at 23 11 47" src="https://github.com/user-attachments/assets/3540fb15-1a5d-4f00-9aec-e4f7706a0a8a">

Default AXIS (no changes upon opening the program):
<img width="126" alt="Screenshot 2024-09-17 at 23 08 05" src="https://github.com/user-attachments/assets/eacd7c41-5036-4617-b74d-0f24ae221e38">

Arial ([issue-preset-arial.json](https://github.com/user-attachments/files/17034326/issue-preset-arial.json) - non-lobby):
<img width="128" alt="Screenshot 2024-09-17 at 23 05 28" src="https://github.com/user-attachments/assets/0e7760ea-decb-4b55-843c-3d9ac3b29d14">
It's probably a bit less visible on Arial since the font's LSBs/RSBs are already small enough initially.

**Comment by Soreepeong** [comment]
![image](https://github.com/user-attachments/assets/51d4c614-3a47-40da-8279-f94ff7b4856a)
![image](https://github.com/user-attachments/assets/6880541b-96b1-43b8-bd9c-e62864079c57)

**Comment by Soreepeong** [comment]
[XivRes.FontGenerator64.zip](https://github.com/user-attachments/files/17035496/XivRes.FontGenerator64.zip)

Can you try this and see if things are working right now?

**Comment by endervad** [comment]
I've tried this one and yes, it looks like everything is fixed, thank you!
On a side note, can you make kerning preview enabled by default? I feel like there needs to be a specific reason to disable it but I might be wrong though.

**Comment by Soreepeong** [comment]
It tends to slow down initial font loading by quite a lot in some cases, so it's turned off by default.

**Comment by endervad** [comment]
Got it, makes sense.
