### ISSUE TITLE
Italic angle is too big with custom fonts

### ISSUE THREAD

**Issue by endervad** [Soreepeong/FFXIV-FontChanger#16]
Whenever you use a custom font instead of AXIS, in-game italics are angled way too much compared to normal italics.

Example preset JSON with Arial (same as in #15): [issue-preset-arial.json](https://github.com/user-attachments/files/17034127/issue-preset-arial.json)
Aside from just changing the font, I also adjusted font sizes and horizontal offsets to more closely match the in-game one.

You can quickly check in-game upon opening any map.
Screenshot of described issue: 
<img width="350" alt="Screenshot 2024-09-17 at 22 27 58" src="https://github.com/user-attachments/assets/f727d7f0-90ba-47e7-8ac2-a0cb93a50921">

**Comment by Soreepeong** [comment]
I think I fixed this problem (same reason w/ #17) but didn't make a release out of it; will check again and I'll make a release after checking #15.

**Comment by Soreepeong** [comment]
![image](https://github.com/user-attachments/assets/a75c9817-aaee-4141-bf0f-e3cdce8b140a)

**Comment by endervad** [comment]
Fixed in https://github.com/Soreepeong/FFXIV-FontChanger/issues/15#issuecomment-2357014089
