### ISSUE TITLE
[Bug] FreeType renderer still missing some fonts.

### ISSUE THREAD

**Issue by toshiya14** [Soreepeong/FFXIV-FontChanger#6]
| | FreeType | DirectWrite |
|-|-----------|--------------|
| Character Information | ![图片](https://user-images.githubusercontent.com/13333533/171115808-c29c2b18-5369-4bd6-95ce-41857e75b33f.png) | ![图片](https://user-images.githubusercontent.com/13333533/171116259-73d8cb4f-f3a0-425e-aa13-7df18d11b5ac.png) |
| Login Queue | ![图片](https://user-images.githubusercontent.com/13333533/171116049-22ba8755-81b5-47b5-b8ad-8b93765f4b63.png) | ![图片](https://user-images.githubusercontent.com/13333533/171116297-00935764-fba7-4c40-9c4a-794d6dbe6356.png) |

I am using FreeType and DirectWrite with the same preset.

Program Version: https://github.com/Soreepeong/FFXIV-FontChanger/issues/5#issuecomment-1141711913

The preset:
https://gist.github.com/toshiya14/38bce63a2bf1f26cb7216e62afa94905

**Comment by Soreepeong** [comment]
[XivRes.FontGenerator64.zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/8807987/XivRes.FontGenerator64.zip)

Try this one. It should fix concurrency problems occurring while using FreeType.

**Comment by Soreepeong** [comment]
Can you try this one? https://github.com/Soreepeong/FFXIV-FontChanger/files/8825723/XivRes.FontGenerator64.zip

I believe I found the reason freetype isn't working correctly, and this should work.

**Comment by toshiya14** [comment]
Yes, thank you. I am sorry for my late reply.
This version works fine.
