### ISSUE TITLE
"Add New" didn't work for me

### ISSUE THREAD

**Issue by endervad** [Soreepeong/FFXIV-FontChanger#9]
Here is ZIP with my config, fonts, and modified `lobby_0_en.exd` for testing:
[Default + Cyrillic (lobby).zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/8818729/Default.%2B.Cyrillic.lobby.zip)
If you try to export with compressing while packing or without compression, the program will silently crash on "Resolving kerning pairs".
If you try to export with compressing after packing, sometimes the program will crash on "Resolving kerning pairs" but after a bunch of attempts it succeeded for me. After importing to TexTools cyrillic glyphs were not added:
(also here one of the AXIS fonts seems to be missing, there should be a version number)
![image](https://user-images.githubusercontent.com/10913278/171501411-0fbd7dd5-004f-42f6-a3fd-9bb5628865c1.png)
![image](https://user-images.githubusercontent.com/10913278/171501509-20c08e10-f767-4a96-ab73-64595ef89512.png)
(and here one of Miedinger fonts is missing)
![image](https://user-images.githubusercontent.com/10913278/171501685-c79bb6bf-b2c9-44a2-a48c-dcc642fbb9b8.png)
I know this issue is a bit identical to the one I've already opened in XivAlexander repo but in this case I've checked the adding method and compared it to the existing presets - I'm pretty sure the way I added is the same.

**Comment by Soreepeong** [comment]
This is the same problem with #6; apparently I haven't handled FreeType correctly yet. Will let you know when I get it right.

**Comment by endervad** [comment]
I see, I'm gonna try with DirectWrite then. By the way, I forgot to mention that I used the build from #6

**Comment by Soreepeong** [comment]
[XivRes.FontGenerator64.zip](https://github.com/Soreepeong/FFXIV-FontChanger/files/8825723/XivRes.FontGenerator64.zip)

Try this one. I believe I found the underlying reason under this problem, and I can now confirm that character selection screen looks fine.

![image](https://user-images.githubusercontent.com/3614868/171677338-be11ef01-2feb-421e-9949-2a465f02ff7d.png)
![image](https://user-images.githubusercontent.com/3614868/171677414-67f064bc-36a2-439f-b3f3-d7b9868d84ef.png)
